// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySfFxQY0qyCvKDPEBaydokI3zq2KdNPI',
    appId: '1:968639263713:web:d0003003a6bf64bd1e98a0',
    messagingSenderId: '968639263713',
    projectId: 'wttapp-f5bbf',
    authDomain: 'wttapp-f5bbf.firebaseapp.com',
    storageBucket: 'wttapp-f5bbf.firebasestorage.app',
    measurementId: 'G-H973ECTR8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93Efm13yJoVVxCfmGSqr-PsY3yV0_gNc',
    appId: '1:968639263713:android:84229f406edab44b1e98a0',
    messagingSenderId: '968639263713',
    projectId: 'wttapp-f5bbf',
    storageBucket: 'wttapp-f5bbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZ5jg0d0T87pD1BkZFMojvyRkoxN57PY',
    appId: '1:968639263713:ios:08be2a1dfe294de81e98a0',
    messagingSenderId: '968639263713',
    projectId: 'wttapp-f5bbf',
    storageBucket: 'wttapp-f5bbf.firebasestorage.app',
    iosBundleId: 'com.example.wttApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZ5jg0d0T87pD1BkZFMojvyRkoxN57PY',
    appId: '1:968639263713:ios:08be2a1dfe294de81e98a0',
    messagingSenderId: '968639263713',
    projectId: 'wttapp-f5bbf',
    storageBucket: 'wttapp-f5bbf.firebasestorage.app',
    iosBundleId: 'com.example.wttApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySfFxQY0qyCvKDPEBaydokI3zq2KdNPI',
    appId: '1:968639263713:web:5b641b0914ee37a21e98a0',
    messagingSenderId: '968639263713',
    projectId: 'wttapp-f5bbf',
    authDomain: 'wttapp-f5bbf.firebaseapp.com',
    storageBucket: 'wttapp-f5bbf.firebasestorage.app',
    measurementId: 'G-EWL49M7BXX',
  );
}
